apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts/
    version: 24.7.4
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml
      
resources:
  - ../../base
  - postgres.yaml

patches:
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: k8tre-tls